### ISSUE TITLE
2. Your first repository!

### ISSUE THREAD

**Issue by byzantinist** [MakeSchool-Tutorials/Introduction-Git-Github-Apps#7]
Grammar:

_9. Most of the files in "changed files" should **disappeared** (you don't need to worry about .DS_Store files)._

should be

_9. Most of the files in "changed files" should **disappear** (you don't need to worry about .DS_Store files)._

------------------------

Consistency:

_Go through the steps to create a repository, commit all the files, and create a remote repository on GitHub for any other projects you have finished at Make School._

uses an Oxford comma whereas most of the Make School syntax does not.

**Comment by dionlarson** [comment]
I am leaving the Oxford comma for now. I would like MS materials to use it more regularly.
